[advisories]
ignore = [
    # Unmaintained crates (Transitive dependencies we cannot easily update)
    "RUSTSEC-2021-0139", # ansi_term (via clap -> rust-music-theory)
    "RUSTSEC-2024-0413", # atk (via gtk -> wry -> nih_plug_webview)
    "RUSTSEC-2024-0416", # atk-sys
    "RUSTSEC-2024-0375", # atty (via nih_log -> nih_plug)
    "RUSTSEC-2025-0057", # fxhash
    "RUSTSEC-2024-0412", # gdk
    "RUSTSEC-2024-0418", # gdk-sys
    "RUSTSEC-2024-0417", # gdkx11
    "RUSTSEC-2024-0414", # gdkx11-sys
    "RUSTSEC-2024-0415", # gtk
    "RUSTSEC-2024-0420", # gtk-sys
    "RUSTSEC-2024-0419", # gtk3-macros
    "RUSTSEC-2024-0436", # paste (via tokenizers)
    "RUSTSEC-2024-0370", # proc-macro-error

    # Unsoundness issues (Transitive dependencies)
    "RUSTSEC-2021-0145", # atty (Potential unaligned read on Windows - We are on macOS)
    "RUSTSEC-2024-0429", # glib (Unsoundness in VariantStrIter - Transitive via wry)
]
