[package]
name = "harmonium"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cpal = { version = "0.15", features = ["wasm-bindgen"] }
fundsp = "0.20.0"
oxisynth = "0.1.0"
rand = "0.8.5"
rust-music-theory = "0.3.0"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"

# Pour l'IA
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = { version = "0.8", default-features = false } 
tokenizers = { version = "0.13.3", default-features = false, features = ["fancy-regex", "unstable_wasm"] } # 'fancy-regex' pour WASM
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
serde_json = "1.0"
getrandom = { version = "0.3", features = ["wasm_js"] }
hound = "3.5.1"
midly = "0.5.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3", features = [
    "console",
    "Window",
    "Document",
    "Navigator",
    "AudioContext",
    "AudioContextOptions",
    "AudioDestinationNode",
    "AudioNode",
    "AudioParam",
    "GainNode",
    "HtmlMediaElement",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "Event",
] }
